### ISSUE TITLE
installing route Unknown blueprint: route

### ISSUE THREAD

**Issue by EmberJSParis** [Vestorly/ember-cli-emblem#56] opened 2017-05-15 08:19 UTC
Hi,

I installed https://github.com/zkwentz/ember-simple-auth-firebase and I read all the issues concerning   code to be inserted in /config/environment.js  ENV.emblemOptions = {
  blueprints: false
}; plus npm install plus bower install plus I updated ember to the version
ember-cli: 2.13.1
node: 6.10.3
os: darwin x64 but I still get installing route Unknown blueprint: route with just above at Function.Addon.lookup (/Users/artedys/authe
ntication/ember-simple-auth-firebase/node_module
s/ember-cli/lib/models/addon.js:1610:27) and where I search for addon.js I find nothing Globally I try to run ember authentication with firebase and I find no program that run. Is someone there who found a solution ? Bug or global ember authenticate with firebase that run in ember-cli: 2.13.1 because the old versions are no longer operational

Here is the entire bug when I type ember g route application

I get

s/ember-cli/lib/models/addon.js:1610:27)
DEPRECATION: Overriding init without calling thi
s._super is deprecated. Please call this._super(
), addon: `Ember CLI ic-ajax`
  at Function.Addon.lookup (/Users/artedys/authe
ntication/ember-simple-auth-firebase/node_module
s/ember-cli/lib/models/addon.js:1610:27)
DEPRECATION: Overriding init without calling thi
s._super is deprecated. Please call `this._super
.init && this._super.init.apply(this, arguments)
;` addon: `torii`
  at Function.Addon.lookup (/Users/artedys/authe
ntication/ember-simple-auth-firebase/node_module
s/ember-cli/lib/models/addon.js:1610:27)
DEPRECATION: Overriding init without calling thi
s._super is deprecated. Please call `this._super
.init && this._super.init.apply(this, arguments)
;` addon: `torii`
  at Function.Addon.lookup (/Users/artedys/authe
ntication/ember-simple-auth-firebase/node_module
s/ember-cli/lib/models/addon.js:1610:27)
installing route
Unknown blueprint: route

**Comment by dhilipsiva** [comment] 2017-06-11 07:58
For anyone facing the same Issue: I had the same error. As a temporary workaround, I just delete `ember-cli-emblem` entry in my `package.json`, generate route and add the package again. Works for me for the time being.

cc @EmberJSParis

**Comment by dhilipsiva** [comment] 2017-06-11 07:59
Also, this issue is a duplicate of https://github.com/Vestorly/ember-cli-emblem/issues/55 . This can probably be closed.

**Comment by joebartels** [comment] 2017-06-16 16:24
thank you for submitting issue - same as #55

**Closed by joebartels** 2017-06-16 16:24 UTC
